### ISSUE TITLE
playground

### ISSUE THREAD

**Issue by Yang725** [huozhi/react-overlay-trigger#35]
大佬，请问overlay-trigger的playground是关闭了嘛？

**Comment by huozhi** [comment]
Hi，项目主页是 https://react-overlay-trigger.vercel.app ，提供了 example，但没有提供编辑 code 的功能。不确定你说的是哪个？我这边可以正常访问，先 close 这个 issue。如果有问题可以继续 comment

**Comment by Yang725** [comment]
那再冒昧问一下，这个项目主页的源码开源了嘛？
